In [1]:
import pandas as pd

In [4]:
file_path = r"E:\my_analysis_projects\british_airways_predictive_model\British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx"
b_a_data = pd.read_excel(file_path)

In [5]:
b_a_data.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [6]:
#checking for nulls
b_a_data.isnull().sum()

FLIGHT_DATE             0
FLIGHT_TIME             0
TIME_OF_DAY             0
AIRLINE_CD              0
FLIGHT_NO               0
DEPARTURE_STATION_CD    0
ARRIVAL_STATION_CD      0
ARRIVAL_COUNTRY         0
ARRIVAL_REGION          0
HAUL                    0
AIRCRAFT_TYPE           0
FIRST_CLASS_SEATS       0
BUSINESS_CLASS_SEATS    0
ECONOMY_SEATS           0
TIER1_ELIGIBLE_PAX      0
TIER2_ELIGIBLE_PAX      0
TIER3_ELIGIBLE_PAX      0
dtype: int64

In [7]:
#copying the file so as not to change the original file
ba_data = b_a_data.copy()

In [8]:
ba_data.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [9]:
ba_data.info

<bound method DataFrame.info of      FLIGHT_DATE FLIGHT_TIME TIME_OF_DAY AIRLINE_CD FLIGHT_NO  \
0     2025-09-02    14:19:00   Afternoon         BA    BA5211
1     2025-06-10    06:42:00     Morning         BA    BA7282
2     2025-10-27    15:33:00   Afternoon         BA    BA1896
3     2025-06-15    18:29:00     Evening         BA    BA5497
4     2025-08-25    20:35:00     Evening         BA    BA1493
...          ...         ...         ...        ...       ...
9995  2025-06-07    22:04:00     Evening         BA    BA7039
9996  2025-04-22    15:15:00   Afternoon         BA    BA9712
9997  2025-08-16    06:11:00     Morning         BA    BA7513
9998  2025-10-24    22:02:00     Evening         BA    BA9958
9999  2025-05-28    22:00:00     Evening         BA    BA8374

     DEPARTURE_STATION_CD ARRIVAL_STATION_CD ARRIVAL_COUNTRY ARRIVAL_REGION  \
0                     LHR                LAX             USA  North America
1                     LHR                LAX             USA  North America
2                     LHR                FRA         Germany         Europe
3                     LHR                IST          Turkey         Europe
4                     LHR                FRA         Germany         Europe
...                   ...                ...             ...            ...
9995                  LHR                VIE         Austria         Europe
9996                  LHR                ORD             USA  North America
9997                  LHR                HND           Japan           Asia
9998                  LHR                DXB             UAE    Middle East
9999                  LHR                DFW             USA  North America

       HAUL AIRCRAFT_TYPE  FIRST_CLASS_SEATS  BUSINESS_CLASS_SEATS  \
0      LONG          B777                  8                    49
1      LONG          B777                  8                    49
2     SHORT          A320                  0                    17
3     SHORT          A320                  0                     8
4     SHORT          A320                  0                    13
...     ...           ...                ...                   ...
9995  SHORT          A320                  0                     7
9996   LONG          B777                  8                    49
9997   LONG          B777                  0                    32
9998   LONG          B787                  8                    48
9999   LONG          B787                  0                    35

      ECONOMY_SEATS  TIER1_ELIGIBLE_PAX  TIER2_ELIGIBLE_PAX  \
0               178                   0                  10
1               178                   0                   7
2               163                   0                  11
3               172                   0                  16
4               167                   0                   6
...             ...                 ...                 ...
9995            173                   1                  15
9996            178                   1                   0
9997            304                   0                   4
9998            200                   1                  10
9999            179                   2                  11

      TIER3_ELIGIBLE_PAX
0                     38
1                     28
2                     40
3                     54
4                     27
...                  ...
9995                  51
9996                   0
9997                  19
9998                  38
9999                  40

[10000 rows x 17 columns]>

In [10]:
ba_data.drop_duplicates()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-06-07,22:04:00,Evening,BA,BA7039,LHR,VIE,Austria,Europe,SHORT,A320,0,7,173,1,15,51
9996,2025-04-22,15:15:00,Afternoon,BA,BA9712,LHR,ORD,USA,North America,LONG,B777,8,49,178,1,0,0
9997,2025-08-16,06:11:00,Morning,BA,BA7513,LHR,HND,Japan,Asia,LONG,B777,0,32,304,0,4,19
9998,2025-10-24,22:02:00,Evening,BA,BA9958,LHR,DXB,UAE,Middle East,LONG,B787,8,48,200,1,10,38
9999,2025-05-28,22:00:00,Evening,BA,BA8374,LHR,DFW,USA,North America,LONG,B787,0,35,179,2,11,40

In [11]:
grouped_data = ba_data.groupby(["TIME_OF_DAY", "ARRIVAL_REGION"])[['FIRST_CLASS_SEATS','BUSINESS_CLASS_SEATS', 'ECONOMY_SEATS', 'TIER1_ELIGIBLE_PAX','TIER2_ELIGIBLE_PAX','TIER3_ELIGIBLE_PAX'  ]].sum()

In [12]:
grouped_data.head()

                            FIRST_CLASS_SEATS  BUSINESS_CLASS_SEATS  \
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                          582                  7216
            Europe                          0                 13901
            Middle East                   576                  7224
            North America                2284                 29834
Evening     Asia                          790                  9841

                            ECONOMY_SEATS  TIER1_ELIGIBLE_PAX  \
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                    36575                  75
            Europe                 231979                 840
            Middle East             39292                 100
            North America          151153                 370
Evening     Asia                    49017                 120

                            TIER2_ELIGIBLE_PAX  TIER3_ELIGIBLE_PAX
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                          1280                4805
            Europe                       10606               40785
            Middle East                   1259                4800
            North America                 5059               19301
Evening     Asia                          1602                6160

In [14]:
# new column for the total number of seats
grouped_data['total_seats'] = grouped_data[['FIRST_CLASS_SEATS','BUSINESS_CLASS_SEATS', 'ECONOMY_SEATS']].sum(axis=1)

In [15]:
# checking percentage of eligible customers per tier
def eligible_customers(tier, total_seats):
    percentage = round((tier/total_seats)*100, 2)
    
    return percentage

In [18]:
#new columns for percent of eligible customers
grouped_data['TIER_1_PERCENT'] = eligible_customers(grouped_data['TIER1_ELIGIBLE_PAX'], grouped_data['total_seats'])
grouped_data['TIER_2_PERCENT'] = eligible_customers(grouped_data['TIER2_ELIGIBLE_PAX'], grouped_data['total_seats'])
grouped_data['TIER_3_PERCENT'] = eligible_customers(grouped_data['TIER3_ELIGIBLE_PAX'], grouped_data['total_seats'])

In [19]:
grouped_data.head()

                            FIRST_CLASS_SEATS  BUSINESS_CLASS_SEATS  \
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                          582                  7216
            Europe                          0                 13901
            Middle East                   576                  7224
            North America                2284                 29834
Evening     Asia                          790                  9841

                            ECONOMY_SEATS  TIER1_ELIGIBLE_PAX  \
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                    36575                  75
            Europe                 231979                 840
            Middle East             39292                 100
            North America          151153                 370
Evening     Asia                    49017                 120

                            TIER2_ELIGIBLE_PAX  TIER3_ELIGIBLE_PAX  \
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                          1280                4805
            Europe                       10606               40785
            Middle East                   1259                4800
            North America                 5059               19301
Evening     Asia                          1602                6160

                            total_seats  TIER_1_PERCENT  TIER_2_PERCENT  \
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                  44373            0.17            2.88
            Europe               245880            0.34            4.31
            Middle East           47092            0.21            2.67
            North America        183271            0.20            2.76
Evening     Asia                  59648            0.20            2.69

                            TIER_3_PERCENT
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                     10.83
            Europe                   16.59
            Middle East              10.19
            North America            10.53
Evening     Asia                     10.33

In [23]:
grouped_data.loc[:, ['TIER_1_PERCENT', 'TIER_2_PERCENT', 'TIER_3_PERCENT']]

                            TIER_1_PERCENT  TIER_2_PERCENT  TIER_3_PERCENT
TIME_OF_DAY ARRIVAL_REGION
Afternoon   Asia                      0.17            2.88           10.83
            Europe                    0.34            4.31           16.59
            Middle East               0.21            2.67           10.19
            North America             0.20            2.76           10.53
Evening     Asia                      0.20            2.69           10.33
            Europe                    0.33            4.45           17.00
            Middle East               0.22            2.59            9.96
            North America             0.21            2.69           10.33
Lunchtime   Asia                      0.15            2.55           10.02
            Europe                    0.39            4.55           17.28
            Middle East               0.19            2.70           10.36
            North America             0.18            2.76           10.49
Morning     Asia                      0.21            2.64           10.18
            Europe                    0.34            4.36           16.74
            Middle East               0.19            2.79           10.60
            North America             0.21            2.83           10.76

In [24]:
lookup_table = grouped_data.reset_index()

In [25]:
lookup_table = lookup_table[['TIME_OF_DAY', 'ARRIVAL_REGION', 'TIER_1_PERCENT', 'TIER_2_PERCENT', 'TIER_3_PERCENT']]

In [26]:
lookup_table

   TIME_OF_DAY ARRIVAL_REGION  TIER_1_PERCENT  TIER_2_PERCENT  TIER_3_PERCENT
0    Afternoon           Asia            0.17            2.88           10.83
1    Afternoon         Europe            0.34            4.31           16.59
2    Afternoon    Middle East            0.21            2.67           10.19
3    Afternoon  North America            0.20            2.76           10.53
4      Evening           Asia            0.20            2.69           10.33
5      Evening         Europe            0.33            4.45           17.00
6      Evening    Middle East            0.22            2.59            9.96
7      Evening  North America            0.21            2.69           10.33
8    Lunchtime           Asia            0.15            2.55           10.02
9    Lunchtime         Europe            0.39            4.55           17.28
10   Lunchtime    Middle East            0.19            2.70           10.36
11   Lunchtime  North America            0.18            2.76           10.49
12     Morning           Asia            0.21            2.64           10.18
13     Morning         Europe            0.34            4.36           16.74
14     Morning    Middle East            0.19            2.79           10.60
15     Morning  North America            0.21            2.83           10.76

In [27]:
lookup_table.to_csv('BA_T3_Lounge_Eligibility_Lookup_Table.csv', index=False)

In [31]:
# exportation purposes only
grouped_table = grouped_data.reset_index()

In [32]:
grouped_table.head()

,TIME_OF_DAY,ARRIVAL_REGION,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,total_seats,TIER_1_PERCENT,TIER_2_PERCENT,TIER_3_PERCENT
0,Afternoon,Asia,582,7216,36575,75,1280,4805,44373,0.17,2.88,10.83
1,Afternoon,Europe,0,13901,231979,840,10606,40785,245880,0.34,4.31,16.59
2,Afternoon,Middle East,576,7224,39292,100,1259,4800,47092,0.21,2.67,10.19
3,Afternoon,North America,2284,29834,151153,370,5059,19301,183271,0.20,2.76,10.53
4,Evening,Asia,790,9841,49017,120,1602,6160,59648,0.20,2.69,10.33

In [33]:
grouped_table.to_csv('cleaned_and_grouped_eligibility_data.csv', index=False)